config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'images#index'
  resources :images,
            only: %i[index show],
            param: :name
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  include ApplicationHelper
  def index
    collection = StorageWrapper.new.fetch_images.map do |image|
      ImageFacade.new(image)
    end

    @pagy, @images = pagy_array(collection)
  end

  def show
    gcp_file = StorageWrapper.new.fetch_by_file_name(
      Base64.urlsafe_decode64(params[:name])
    )

    respond_to do |format|
      format.html do
        @image = ImageFacade.new(gcp_file)
      end
      format.jpeg do
        send_data(gcp_file.download.read, filename: "#{file_prefix}_image_#{gcp_file.name[..12]}.jpeg",
                                          type: 'image/jpeg')
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
  def file_prefix
    ENV.fetch('FILE_PREFIX')
  end
end

app/views/images/index.html.erb
<div class="flex flex-col ">
  <div class="flex justify-center">
    <%== pagy_nav(@pagy) %>
  </div>
  <div class="flex flex-row flex-wrap justify-left gap-6">
    <% @images.each do |image| %>
      <div class="bg-indigo-300">
        <%= link_to image_path(image.name_url_safe_encoded) do %>
          <%= image_tag image.signed_url, class: "h-48 w-48" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/images/show.html.erb
<div class="flex flex-col ">
  <div>
    <p>
      Links to:
    </p>
    <ul>
      <li>
        <%= link_to 'index images', images_path %>
      </li>
      <li>
        <%= link_to 'download a image', image_path(@image.name_url_safe_encoded, format: :jpeg) %>
      </li>
    </ul>
  </div>
  <div class="flex flex-row justify-center">
    <div class="bg-indigo-300">
      <%= image_tag @image.signed_url, class: "h-192 w-192" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--

  _______   _       _                                          __   _
 |__   __| | |     (_)                                        / _| | |
    | |    | |__    _   _ __     __ _    ___   _ __    __ _  | |_  | |_
    | |    | '_ \  | | | '_ \   / _` |  / __| | '__|  / _` | |  _| | __|
    | |    | | | | | | | | | | | (_| | | (__  | |    | (_| | | |   | |_
    |_|    |_| |_| |_| |_| |_|  \__, |  \___| |_|     \__,_| |_|    \__|
                                   | |
                                   |_|

  Want to be part of an amazing team?
  Get in touch ~ https://www.thinqcraft.com/

-->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Gcsbrowsertest</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <main class="container mx-auto mt-4">
    <%= yield %>
  </main>
</body>
</html>